# Generated by Django 3.0.5 on 2020-04-20 20:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200420_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3000), default=[], size=None),
            preserve_default=False,
        ),
    ]
