# Generated by Django 3.0.5 on 2020-04-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_cuisines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='total_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
