# Generated by Django 3.0.5 on 2020-04-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20200421_1645'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recipe',
            name='recipes_rec_rating_e9153a_idx',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='rating',
            new_name='rating_value',
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['rating_value'], name='recipes_rec_rating__e43bcc_idx'),
        ),
    ]
