# Generated by Django 3.0.5 on 2020-06-01 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20200428_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='cuisine',
            options={'ordering': ('name',)},
        ),
    ]
