# Generated by Django 3.0.5 on 2020-07-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cuisines',
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
    ]
