# Generated by Django 3.0.5 on 2020-12-06 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20200714_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
