# Generated by Django 3.0.5 on 2022-08-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_recipe_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_time_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
