# Generated by Django 3.0.5 on 2022-08-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_recipe_total_time_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='total_time',
        ),
    ]
