# Generated by Django 3.2.20 on 2025-01-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_remove_recipe_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('special_diets', 'special_diets'), ('cuisines', 'cuisines'), ('meal_types', 'meal_types'), ('dish_types', 'dish_types'), ('_UNKNOWN_', '_UNKNOWN_')], max_length=50),
        ),
    ]
