# Generated by Django 3.2.20 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_alter_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rating_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
